# Generated by Django 5.1.1 on 2024-10-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPUsage',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('free_sessions_used', models.PositiveIntegerField(default=0)),
                ('last_usage_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
